[workspace]
members = [
    "crates/mfl",
    "crates/intcast",
    "crates/tester",
    "crates/lexer",
    "crates/stores",
    "crates/lsp_server",
]
resolver = "2"

[profile.release]
debug = true
