[package]
name = "porth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11.1"
color-eyre = "0.5.11"
structopt = "0.3.23"
